language: ruby

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:migrate
  - bundle exec rails test
